# Generated by Django 4.1.13 on 2024-05-22 03:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('cart_items', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), size=None)),
                ('total_price', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
    ]
