# Generated by Django 4.1.13 on 2024-05-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipment_updates', '0002_shipment_created_at_alter_shipment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment_updates.shipment')),
            ],
            options={
                'db_table': 'shipment_status',
            },
        ),
    ]
