# Generated by Django 4.1.13 on 2024-04-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField()),
                ('cart_items', models.TextField()),
                ('total_price', models.BigIntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'initiate_payment',
            },
        ),
    ]
