# Generated by Django 4.1.13 on 2024-04-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiate_payment', '0002_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiate_payment.paymentmode'),
        ),
    ]
